version: "3"
services:
  ms1:
    container_name: microservice1
    build: 
      context: ./microservice1
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    depends_on:
    - ms2
  ms2:
    container_name: microservice2
    build: 
      context: ./microservice2
      dockerfile: Dockerfile
    ports:
    - "3000:3000"
    depends_on:
    - ms3
  ms3:
    container_name: microservice3
    build: 
      context: ./microservice3
      dockerfile: Dockerfile
    ports:
    - "3000:3000"